import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React, { useState } from 'react'


import { useDispatch, useSelector } from '../store/store';
import { getRecordState, ReadingRecordState, setRecordList } from '../store/slices/recordSlice'


const Home: NextPage = () => {

  const dispatch = useDispatch();
  const { recordList } = useSelector(getRecordState);

  const [isSelectUploadImage, setIsSelectUploadImage] = useState(true)
  const [previewImage, setPreviewImage] = useState('')


  const handleTypeImage = (e: any) => {
    setIsSelectUploadImage(e.target.id === 'uploadImage' ? true : false)
    setPreviewImage('')
  }

  const handlePreviewImage = (e: any) => {
    if (isSelectUploadImage) {
      if (!e.target.files || e.target.files.length === 0) {
        return
      }
      const imageURL = URL.createObjectURL(e.target.files[0])
      setPreviewImage(imageURL)
    } else {
      setPreviewImage(e.target.value)
    }
  }

  const handleSubmitForm = ({
    bookTitle,
    date,
    readTime,
  }: ReadingRecordState) => {

    const payload: ReadingRecordState = {
      bookTitle: bookTitle,
      date: date,
      readTime: readTime,
      image: previewImage,
    }
    /* TODO Submit redux */
    dispatch(setRecordList(payload));
  }

  console.log('recordList', recordList)
  return (
    <div className={styles.container}>
      <Head>
        <title>Reading record</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Reading record</h1>


      <form
        onSubmit={(e: React.SyntheticEvent) => {
          e.preventDefault();
          const target = e.target as typeof e.target & {
            bookTitle: { value: string };
            date: { value: string };
            readTime: { value: number };
            // typeImage: { value: string };
            // image: { value: any };
          };
          const bookTitle: string = target.bookTitle.value; // typechecks!
          const date: string = target.date.value; // typechecks!
          const readTime: number = Number(target.readTime.value); // typechecks!

          const payload: ReadingRecordState = {
            bookTitle: bookTitle,
            date: date,
            readTime: readTime,
          }
          handleSubmitForm(payload)

        }}
      >
        <div>
          <label>
            Title of book:
            <input
              type="text"
              name="bookTitle"
              placeholder='Title of book'
            />
          </label>
        </div>

        <div>
          <label>
            Date:
            <input
              type="date"
              name="date"
              placeholder='Date'
            />
          </label>
        </div>

        <div>
          <label>
            Read time (Hrs):
            <input
              type="number"
              step="0.5"
              pattern="[0-9\/]"
              name="readTime"
              placeholder='Read time'
            />
          </label>
        </div>

        <div>
          <input
            onChange={(e) => handleTypeImage(e)}
            checked={isSelectUploadImage}
            name="typeImage" value="uploadImage" id="uploadImage" type="radio" /><label>Upload image</label>
          <input
            onChange={(e) => handleTypeImage(e)}
            name="typeImage" value="linkImage" id="linkImage" type="radio" /><label>Link image</label>
        </div>

        <div>
          {isSelectUploadImage ?
            (
              <>
                <div>
                  <label>
                    Upload image:
                    <input
                      type="file"
                      accept="image/png, image/jpeg"
                      name="image"
                      placeholder='Upload image'
                      onChange={(e) => handlePreviewImage(e)}
                    />
                  </label>
                </div>
              </>
            )
            :
            (
              <>
                <div>
                  <label>
                    Link image:
                    <input
                      type="text"
                      name="image"
                      placeholder='Link image'
                      onChange={(e) => handlePreviewImage(e)}
                    />
                  </label>
                </div>
              </>
            )
          }
          {(
            previewImage.includes('http') ||
            previewImage.includes('https')
          ) &&
            (
              <>
                <div>
                  <Image
                    loader={() => previewImage}
                    src={previewImage}
                    alt='previewImage'
                    width={200}
                    height={200}
                  />
                </div>
              </>
            )
          }
        </div>


        <div>
          <input type="submit" value="Submit" />
        </div>
      </form>


    </div>
  )
}

export default Home
